# Generated by Django 5.0.7 on 2024-08-01 21:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=8, max_digits=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('description', models.CharField(max_length=500)),
                ('active', models.IntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE')], default=1)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance_restful.bankaccount')),
                ('saving_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance_restful.savingtypes')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.UUID('f7bc72ae-163e-4971-a4c9-662a88e4fa20'), editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('type_of_transaction', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal')])),
                ('description', models.CharField(max_length=500)),
                ('transaction_date', models.DateTimeField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance_restful.bankaccount')),
                ('transaction_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='finance_restful.transactiontypes')),
            ],
        ),
    ]
