# Generated by Django 5.0.7 on 2024-08-02 18:13

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_restful', '0002_bankaccount_account_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('0f1c34d0-2999-4677-ac5a-dcce8e775313'), editable=False, unique=True),
        ),
    ]
