# Generated by Django 5.0.7 on 2024-08-02 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_restful', '0003_alter_transactions_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(default=uuid.UUID('fbec9531-2270-4b84-b1e6-bd0ff6b77516'), editable=False, unique=True),
        ),
    ]
