# Generated by Django 5.0.7 on 2024-08-02 21:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_restful', '0004_alter_transactions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(auto_created=uuid.UUID('cb7804f3-a5b0-455d-a983-cbfe36cb5e0d'), editable=False, unique=True),
        ),
    ]
