# Generated by Django 5.0.7 on 2024-08-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_restful', '0006_alter_transactions_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.IntegerField(choices=[(2, 'Saving Account'), (1, 'Main Account')], null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='description',
            field=models.CharField(null=True),
        ),
    ]
