# Generated by Django 5.0.7 on 2024-08-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_restful', '0007_bankaccount_account_type_bankaccount_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20, null=True),
        ),
    ]
