# Generated by Django 5.0.7 on 2024-08-04 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_restful', '0008_alter_bankaccount_current_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontypes',
            name='type',
            field=models.IntegerField(choices=[(1, 'Credit'), (2, 'Debit')], null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.IntegerField(choices=[(3, 'Business Account'), (2, 'Saving Account'), (1, 'Main Account')], null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type_of_transaction',
            field=models.IntegerField(choices=[(1, 'Credit'), (2, 'Debit')]),
        ),
    ]
